# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content
server:
  error:
    include-message: always

spring:
  jpa:
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
    mongodb:
      uri: mongodb://localhost:27017/movie
  jackson:
    serialization:
      write-dates-as-timestamps: false

spring-rest-movie:
  security:
    enabled: false

gateway:
  omdb:
    url: http://www.omdbapi.com/
    apiKey: a5383af4

logging:
  level:
    root: INFO
    br.com.iworks: INFO